# TinyGo for the PlayStation 2, ready to use: the ps2dev SDK and toolchain
# (from the ps2dev image), Go, Python (for the demos' scripts) and this
# fork's TinyGo from its release tarball.
#
#   docker run --rm -v "$PWD:/src" ghcr.io/rgsilva/tinygo-ps2:dev tinygo build -target ps2 -o out.elf .
#
# Built by the Linux workflow for amd64 and arm64: the tarball of the
# platform being built (tinygo-ps2.linux-<arch>.tar.gz) is copied in.
FROM ps2dev/ps2dev:v2.0.0

ARG GO_VERSION=1.27.1
ARG TARGETARCH

RUN apk add --no-cache bash ca-certificates git make python3 \
 && wget -qO- "https://go.dev/dl/go${GO_VERSION}.linux-${TARGETARCH}.tar.gz" | tar -C /usr/local -xz

COPY tinygo-ps2.linux-${TARGETARCH}.tar.gz /tmp/tinygo.tar.gz
RUN tar -C /opt -xzf /tmp/tinygo.tar.gz && rm /tmp/tinygo.tar.gz

ENV PATH="/opt/tinygo/bin:/usr/local/go/bin:${PATH}" \
    PS2DEV=/usr/local/ps2dev \
    GOPATH=/go \
    GOFLAGS=-buildvcs=false
WORKDIR /src
